apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: html-landing
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/docode-id/html-landing.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false