apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-landing
  namespace: default
  labels:
    app: html-landing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: html-landing
  template:
    metadata:
      labels:
        app: html-landing
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-content
        configMap:
          name: html-landing-content