apiVersion: v1
kind: Service
metadata:
  name: html-landing
  namespace: default
  labels:
    app: html-landing
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: html-landing